### ISSUE TITLE
这个网页里面的对话制作完成后如何生成视频呢？

### ISSUE THREAD

**Issue by xujimu** [cuifengcn/wechat-video-generate#1]
感谢大佬做出这么棒的东西 http://127.0.0.1:36999/ 是什么？这个网页里面的对话制作完成后如何生成视频呢？

**Comment by EnshengYuan** [comment]
点生成能直接生成视频的，猜想是这不报错了，browser = playwright.chromium.launch(headless=True)，这里需要playwright install一下，为了安装浏览器内核
