### ISSUE TITLE
运行后，功能是没有做出来还是我哪里出错了

### ISSUE THREAD

**Issue by kx1115** [cuifengcn/wechat-video-generate#5]
如题，好不容易把环境搞好跑起来了，但功能好像都没实现。
1.首页搜索图片没有反应
2.点生成后，找开的本地网站，只有编辑聊天内容的，没有生成图片及视频的按钮

这样到底是我们边的配置问题还是本项目功能没有实现啊？

**Comment by TaleAi** [comment]
需要升级下flet
